---
title: "BiocRevSumm: LLM-based summaries for Bioconductor package submissions"
shorttitle: "Bioconductor submissions"
author: "Vincent J. Carey, stvjc at channing.harvard.edu"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{BiocRevSumm: LLM-based summaries for Bioconductor package submissions}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
---

# Introduction

This package surveys issues in the Bioconductor contributions repositories
with the aim of producing a structured summary of package objectives
and capabilities.

# Enumerating packages in review

```{r geto, message=FALSE}
library(BiocRevSumm)
iss = get_repos_from_open_issues("bioconductor", "contributions")
head(iss)
```

# Finding the vignettes for high-resolution categorization

```{r getv}
rs = get_repos_from_open_issues("bioconductor", "contributions")
lk1 = strsplit(rs, "\\/")[[1]]
ghuser = lk1[4]
ghrepo = lk1[5]
lkvigs = list_github_dir(user = ghuser, repo = ghrepo, path="vignettes") 
vigs = grep("Rmd", lkvigs, value=TRUE)
# arbitrarily choose first
build_vignette_path = function(ghuser, ghrepo, branch, vname) {
  sprintf(
    "https://raw.githubusercontent.com/%s/%s/refs/heads/%s/vignettes/%s",
     ghuser, ghrepo, branch, vname
     )
   }
url = build_vignette_path(ghuser, ghrepo, vigs[1])
url
```

# Summarize a selected vignette

```{r dosumm, results="asis"}
ans = vig2data(url)
writeLines(strwrap(ans$focused, 75))
```

# Collect summaries, and categorize them

```{r dofull}
issusers = sapply(strsplit(rs, "\\/"), "[", 4)
issrepos = sapply(strsplit(rs, "\\/"), "[", 5)
nrep = length(issusers)
find_existing_branch <- function(user, repo, path, branches = c("main", "master", "devel")) {
  for (branch in branches) {
    url <- sprintf("https://api.github.com/repos/%s/%s/contents/%s?ref=%s", user, repo, path, branch)
    res <- tryCatch({
      r <- httr::GET(url)
      if (httr::status_code(r) == 200) return(branch)
      else stop("Not found")
    }, error = function(e) NULL)
    if (!is.null(res)) return(res)
  }
  return(NA)  # None found
}

vpaths = sapply(seq_len(nrep), function(i) {
   br = find_existing_branch(issusers[i], issrepos[i], path="vignettes", branches = c("main", "master", "devel"))
   if (is.na(br)) return(NA)
   cat(i)
   Sys.sleep(5)
   vd = try(list_github_dir(user = issusers[i], repo = issrepos[i], branch=br, path="vignettes"), silent=TRUE)
   if (inherits(vd, "try-error")) return(NA)
   vn = grep("Rmd|Rnw", vd, value=TRUE)[1]
   build_vignette_path(issusers[i], issrepos[i], branch=br, vn)
   })
```
