#' an app to survey submission content generated by AI summary using EDAM
#' @import shiny
#' @export
demo_app = function() {
  dat = dir(system.file("rds", package="BiocRevSumm"))
  fpaths = dir(system.file("rds", package="BiocRevSumm"), full=TRUE)
  pngpaths = dir(system.file("pngs", package="BiocRevSumm"), full=TRUE)
  dd = strsplit(dat, "_")
  repo = sapply(dd, "[", 1)
  pkgs = sapply(dd, "[", 2)
  pkgs = gsub(".rds$", "", pkgs)
  names(fpaths) = pkgs
  names(pngpaths) = pkgs
  ui = fluidPage(
   sidebarLayout(
    sidebarPanel(
     helpText("BiocRevSumm: packages in review"),
     selectInput("pkg", "package", sort(pkgs))
     ),
    mainPanel(
     tabsetPanel(
      tabPanel("txt", verbatimTextOutput("txt")),
      tabPanel("txt2", uiOutput("txt2")),
      tabPanel("edam", imageOutput("edamg")),
      tabPanel("about", helpText("show info about pkg"))
     )
    )
   )
  )

  server = function(input, output) {
   cont = reactive({
    txt = readRDS(fpaths[input$pkg])
    imgpath = pngpaths[input$pkg]
    txt$focused = strwrap(txt$focused, 75)
    list(txt=txt, imgpath=imgpath)
   })
   output$txt = renderPrint({
    cont()
   })
   output$txt2 = renderText({
    HTML(markdown::markdownToHTML(text=cont()$txt$focused, fragment.only=TRUE))
    })
   output$edamg = renderImage({
    cc = cont()
    list(
     src = cc$imgpath,
     contentType = 'image/png',
     width=800, height=800, alt="EDAM subgraph")
    }, deleteFile = FALSE)
    
}

runApp(list(ui=ui, server=server))
    
}
